// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace APP.API.Models
{
    public partial class appdbContext : DbContext
    {
        public appdbContext()
        {
        }

        public appdbContext(DbContextOptions<appdbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Defaultuser> Defaultuser { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("utf8mb4_0900_ai_ci")
                .HasCharSet("utf8mb4");

            modelBuilder.Entity<Defaultuser>(entity =>
            {
                entity.HasKey(e => e.Iddefaultuser)
                    .HasName("PRIMARY");

                entity.ToTable("defaultuser");

                entity.Property(e => e.Iddefaultuser)
                    .ValueGeneratedNever()
                    .HasColumnName("iddefaultuser");

                entity.Property(e => e.UserName)
                    .IsRequired()
                    .HasMaxLength(45)
                    .HasColumnName("userName");

                entity.Property(e => e.UserPassword)
                    .IsRequired()
                    .HasMaxLength(45)
                    .HasColumnName("userPassword");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}